/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";
import { ValariApi } from "@fern-api/valari";

export class BadRequestError extends errors.ValariApiError {
    constructor(body: ValariApi.ErrorBody) {
        super({
            message: "BadRequestError",
            statusCode: 400,
            body: body,
        });
        Object.setPrototypeOf(this, BadRequestError.prototype);
    }
}
