/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ValariApi } from "@fern-api/valari";
import * as core from "../../../../core";

export const Application: core.serialization.ObjectSchema<serializers.Application.Raw, ValariApi.Application> =
    core.serialization.object({
        data: core.serialization.lazyObject(async () => (await import("../../..")).ApplicationData),
    });

export declare namespace Application {
    interface Raw {
        data: serializers.ApplicationData.Raw;
    }
}
