/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ValariApi } from "@fern-api/valari";
import * as core from "../../../../core";

export const LinkSession: core.serialization.ObjectSchema<serializers.LinkSession.Raw, ValariApi.LinkSession> =
    core.serialization.object({
        message: core.serialization.string().optional(),
        data: core.serialization.lazyObject(async () => (await import("../../..")).LinkSessionData).optional(),
    });

export declare namespace LinkSession {
    interface Raw {
        message?: string | null;
        data?: serializers.LinkSessionData.Raw | null;
    }
}
