/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ValariApi } from "@fern-api/valari";
import * as core from "../../../../core";

export const LinkSessionData: core.serialization.ObjectSchema<
    serializers.LinkSessionData.Raw,
    ValariApi.LinkSessionData
> = core.serialization.object({
    type: core.serialization.string().optional(),
    attributes: core.serialization.lazyObject(async () => (await import("../../..")).LinkSessionsAttributes),
    id: core.serialization.string().optional(),
});

export declare namespace LinkSessionData {
    interface Raw {
        type?: string | null;
        attributes: serializers.LinkSessionsAttributes.Raw;
        id?: string | null;
    }
}
