/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ValariApi } from "@fern-api/valari";
import * as core from "../../../../core";

export const Relationships: core.serialization.ObjectSchema<serializers.Relationships.Raw, ValariApi.Relationships> =
    core.serialization.object({
        application: core.serialization.lazyObject(async () => (await import("../../..")).Application).optional(),
        businessApplication: core.serialization
            .lazyObject(async () => (await import("../../..")).BusinessApplicationData)
            .optional(),
    });

export declare namespace Relationships {
    interface Raw {
        application?: serializers.Application.Raw | null;
        businessApplication?: serializers.BusinessApplicationData.Raw | null;
    }
}
