/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ValariApi } from "@fern-api/valari";
import * as core from "../../../../core";

export const SessionType: core.serialization.Schema<serializers.SessionType.Raw, ValariApi.SessionType> =
    core.serialization.enum_(["person-application", "business-application", "account-details", "send-payment"]);

export declare namespace SessionType {
    type Raw = "person-application" | "business-application" | "account-details" | "send-payment";
}
