/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class ValariApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, ValariApiTimeoutError.prototype);
    }
}
