/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ApplicationData {
    /** UUID of Application Resource */
    id?: string;
    /** Application */
    type?: string;
}
