/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Business Application Relationship
 */
export interface BusinessApplicationData {
    /** UUID of Business Application */
    id?: string;
    /** Business Application */
    type?: string;
}
