/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface LinkSessionsAttributes {
    status?: string;
    sessionType?: string;
    expiresAt?: string;
    ip?: string;
    longitude?: string;
    latitude?: string;
    errorUrl?: string;
    successUrl?: string;
    webviewUrl?: string;
    isExpired?: boolean;
}
