/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { ValariApi } from "@fern-api/valari";

/**
 * Link Session Relationships
 */
export interface Relationships {
    /** Application */
    application?: ValariApi.Application;
    /** Business Application Relationship */
    businessApplication?: ValariApi.BusinessApplicationData;
}
