/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Type of Session to initialize
 */
export type SessionType = "person-application" | "business-application" | "account-details" | "send-payment";

export const SessionType = {
    PersonApplication: "person-application",
    BusinessApplication: "business-application",
    AccountDetails: "account-details",
    SendPayment: "send-payment",
} as const;
