/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { ValariApi } from "@fern-api/valari";

export interface CreateALinkSessionRequest {
    data: ValariApi.LinkSessionData;
}
