/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AttributesRequest {
    /** Partner ID */
    partnerId: string;
    /** Partner Secret from Access Credentials */
    partnerSecret: string;
    /** Oauth 2.0 Grant Type */
    grantType: string;
    /** 8-32 Characters */
    appKey: string;
}
