/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AuthenticationAttributes {
    token?: string;
    appKey?: string;
    partnerId?: string;
    grantType?: string;
}
