/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ValariApi } from "@fern-api/valari";
import * as core from "../../../../core";

export const LinkSessionType: core.serialization.Schema<serializers.LinkSessionType.Raw, ValariApi.LinkSessionType> =
    core.serialization.enum_([
        "depositAccount",
        "authorizedUser",
        "customer",
        "businessCustomer",
        "application",
        "businessApplication",
    ]);

export declare namespace LinkSessionType {
    type Raw =
        | "depositAccount"
        | "authorizedUser"
        | "customer"
        | "businessCustomer"
        | "application"
        | "businessApplication";
}
