/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { ValariApi } from "@fern-api/valari";
import * as core from "../../core";

export const AuthenticationAttributes: core.serialization.ObjectSchema<
    serializers.AuthenticationAttributes.Raw,
    ValariApi.AuthenticationAttributes
> = core.serialization.object({
    token: core.serialization.string().optional(),
    appKey: core.serialization.string().optional(),
    partnerId: core.serialization.string().optional(),
    grantType: core.serialization.string().optional(),
});

export declare namespace AuthenticationAttributes {
    interface Raw {
        token?: string | null;
        appKey?: string | null;
        partnerId?: string | null;
        grantType?: string | null;
    }
}
