/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { ValariApi } from "@fern-api/valari";
import * as core from "../../core";

export const AuthenticationData: core.serialization.ObjectSchema<
    serializers.AuthenticationData.Raw,
    ValariApi.AuthenticationData
> = core.serialization.object({
    type: core.serialization.string().optional(),
    attributes: core.serialization.lazyObject(async () => (await import("..")).AuthenticationAttributes).optional(),
});

export declare namespace AuthenticationData {
    interface Raw {
        type?: string | null;
        attributes?: serializers.AuthenticationAttributes.Raw | null;
    }
}
