/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { ValariApi } from "@fern-api/valari";

export interface LinkSessionData {
    type?: string;
    attributes: ValariApi.LinkSessionsAttributes;
    id?: string;
}
