/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ErrorBody {
    errorType?: string;
    errorMessage?: string;
    errors?: string[];
    errorRaw?: string;
    errorsValidation?: string;
}
