/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const ValariApiEnvironment = {
    Production: "https://sandbox.valari.co/api/v1",
} as const;

export type ValariApiEnvironment = typeof ValariApiEnvironment.Production;
