/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const ValariApiEnvironment = {
    Sandbox: "https://sandbox.valari.co/api/v1",
    Production: "https://app.valari.co/api/v1",
} as const;

export type ValariApiEnvironment = typeof ValariApiEnvironment.Sandbox | typeof ValariApiEnvironment.Production;
