/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { ValariApi } from "@fern-api/valari";
import * as core from "../../../../../core";

export const CreateAuthenticationTokenRequest: core.serialization.Schema<
    serializers.CreateAuthenticationTokenRequest.Raw,
    ValariApi.CreateAuthenticationTokenRequest
> = core.serialization.object({
    type: core.serialization.string(),
    attributes: core.serialization.lazyObject(async () => (await import("../../../..")).AttributesRequest),
});

export declare namespace CreateAuthenticationTokenRequest {
    interface Raw {
        type: string;
        attributes: serializers.AttributesRequest.Raw;
    }
}
