/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ValariApi } from "@fern-api/valari";
import * as core from "../../../../core";

export const ErrorBody: core.serialization.ObjectSchema<serializers.ErrorBody.Raw, ValariApi.ErrorBody> =
    core.serialization.object({
        errorType: core.serialization.string().optional(),
        errorMessage: core.serialization.string().optional(),
        errors: core.serialization.list(core.serialization.string()).optional(),
        errorRaw: core.serialization.string().optional(),
        errorsValidation: core.serialization.string().optional(),
    });

export declare namespace ErrorBody {
    interface Raw {
        errorType?: string | null;
        errorMessage?: string | null;
        errors?: string[] | null;
        errorRaw?: string | null;
        errorsValidation?: string | null;
    }
}
